[[projects]]
name = "samhuri.net"
title = "samhuri.net"
description = "this site"
url = "https://github.com/samsonjs/samhuri.net"

[[projects]]
name = "bin"
title = "bin"
description = "my collection of scripts in ~/bin"
url = "https://github.com/samsonjs/bin"

[[projects]]
name = "config"
title = "config"
description = "important dot files (zsh, emacs, vim, screen)"
url = "https://github.com/samsonjs/config"

[[projects]]
name = "compiler"
title = "compiler"
description = "a compiler targeting x86 in Ruby"
url = "https://github.com/samsonjs/compiler"

[[projects]]
name = "lake"
title = "lake"
description = "a simple implementation of Scheme in C"
url = "https://github.com/samsonjs/lake"

[[projects]]
name = "AsyncMonitor"
title = "AsyncMonitor"
description = "easily monitor async sequences using Swift concurrency"
url = "https://github.com/samsonjs/AsyncMonitor"

[[projects]]
name = "NotificationSmuggler"
title = "NotificationSmuggler"
description = "embed strongly-typed values in notifications on Apple platforms"
url = "https://github.com/samsonjs/NotificationSmuggler"

[[projects]]
name = "strftime"
title = "strftime"
description = "strftime for JavaScript"
url = "https://github.com/samsonjs/strftime"

[[projects]]
name = "format"
title = "format"
description = "printf for JavaScript"
url = "https://github.com/samsonjs/format"

[[projects]]
name = "gitter"
title = "gitter"
description = "a GitHub client for Node (v3 API)"
url = "https://github.com/samsonjs/gitter"

[[projects]]
name = "cheat.el"
title = "cheat.el"
description = "cheat from emacs"
url = "https://github.com/samsonjs/cheat.el"
