author = "Sami Samhuri"
email = "sami@samhuri.net"
title = "samhuri.net"
description = "Sami Samhuri's blog about programming, mainly about iOS and Ruby and Rails these days."
url = "https://samhuri.net"
fediverse_creator = "@sjs@techhub.social"
image_url = "/images/me.jpg"
scripts = []
styles = ["/css/normalize.css", "/css/style.css", "/css/syntax.css"]
plugins = ["posts", "projects"]

[projects_plugin]
scripts = [
  "https://ajax.googleapis.com/ajax/libs/prototype/1.6.1.0/prototype.js",
  "/js/gitter.js",
  "/js/store.js",
  "/js/projects.js"
]
styles = []

[outputs.html]
remote_links = [
  {"label": "Mastodon", "href": "https://techhub.social/@sjs", "icon": "mastodon"},
  {"label": "GitHub", "href": "https://github.com/samsonjs", "icon": "github"},
  {"label": "RSS", "href": "/feed.xml", "icon": "rss"},
  {"label": "Gemini", "href": "gemini://samhuri.net", "icon": "gemini"}
]

[outputs.gemini]
recent_posts_limit = 20
home_links = [
  "/about",
  "/posts",
  "/projects",
  "https://techhub.social/@sjs",
  "https://github.com/samsonjs",
  "/posts/feed.gmi",
  "https://samhuri.net/feed.xml",
  "mailto:sami@samhuri.net"
]
exclude_public = [
  "tweets/**",
  "css/**",
  "js/**",
  "apple-touch-icon.png",
  "favicon.ico",
  "favicon.gif",
  "robots.txt",
  "humans.txt",
  "isitmycakeday.html"
]
