author = "Sami Samhuri"
email = "sami@samhuri.net"
title = "samhuri.net"
description = "Sami Samhuri's blog about programming, mainly about iOS and Ruby and Rails these days."
url = "https://samhuri.net"
image_url = "/images/me.jpg"
scripts = []
styles = ["css/normalize.css", "css/style.css", "css/syntax.css"]

[projects_plugin]
scripts = [
  "https://ajax.googleapis.com/ajax/libs/prototype/1.6.1.0/prototype.js",
  "js/gitter.js",
  "js/store.js",
  "js/projects.js"
]
styles = []
